version: "3"
services:
  web:
  # replace username/repo:tag with your name and image details
    image: tomcat:8
    deploy:
      replicas: 2 
      restart_policy:
        condition: on-failure
    ports:
      - "11077:8080"
    volumes:
     - /usr/local/capstone:/usr/local/tomcat/webapps
    networks:
      - webnet
networks:
  webnet:
