// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class Seletng {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver" );
    System.setProperty("webdriver.gecko.driver","/usr/bin/geckodriver");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  public static void wait(int ms)
  {
      try
      {
          Thread.sleep(ms);
      }
      catch(InterruptedException ex)
      {
          Thread.currentThread().interrupt();
      }
  }
  
  @Test
  public void untitled() {
	driver = new ChromeDriver();
    //driver = new FirefoxDriver();
    driver.get("http://localhost:9095/capstone/login");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("atul.koshta@wipro.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("pass");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("9782370610201")).click();
    wait(2000);

    new WebDriverWait(driver, 5).until(ExpectedConditions.elementToBeClickable(By.cssSelector("#email"))).click();
    //driver.findElement(By.id("email")).click();
    wait(2000);
    driver.findElement(By.id("email")).sendKeys("v.s@gmail.com");
    driver.findElement(By.cssSelector(".modal-footer:nth-child(4) > #submitButton")).click();
    driver.findElement(By.id("issue-model-close-button")).click();
    driver.findElement(By.cssSelector(".fa-sign-out")).click();
    driver.close();
  }
}
