// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class Stest {
  private static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void stest() {
	WebDriver driver = new ChromeDriver();
    driver.get("http://localhost:9095/capstone/login");
    driver.manage().window().setSize(new Dimension(738, 816));
    driver.findElement(By.linkText("Forgot Password?")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("v.s@gmail.com");
    driver.findElement(By.id("dob")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > .day:nth-child(5)")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("like");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("v.s@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("like");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.close();
  }
}
